node {
    docker.image('node:16-buster-slim').inside('-p 4000:4000') {
        stage('Build') {
            sh 'npm install'
        }
        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }
        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap deploy?'
        }
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'

            withCredentials([gitUsernamePassword(credentialsId: 'alfayeddennita-github-token', gitToolName: 'Default')]) {
                sh './jenkins/scripts/push.sh'
            }

            sleep time: 1, unit: 'MINUTES'
            sh './jenkins/scripts/kill.sh'
        }
    }
}
