node {
    docker.image('node:16-buster-slim').inside('-p 4000:4000') {
        stage('Build') {
            sh 'npm install'
        }
        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }
        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap deploy?'
        }
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            // sleep time: 1, unit: 'MINUTES'
            sh './jenkins/scripts/kill.sh'
        }
    }
    stage('Deploy Vercel') {
        withCredentials([gitUsernamePassword(credentialsId: 'alfayeddennita-github-token', gitToolName: 'Default')]) {
            sh 'git config --global user.name "Jenkins Pipeline"'
            sh 'git config --global user.email "jenkins@localhost"'
            sh 'git pull https://github.com/AlfayedDennita/dicoding-cicd-react.git HEAD:main'
            sh 'git add --all'
            sh 'git commit -m "Deploy from Jenkins pipeline"'
            sh 'git push -u https://github.com/AlfayedDennita/dicoding-cicd-react.git HEAD:main'
        }
    }
}
